AllCops:
  Exclude:
   - db/schema.rb
   - vendor/**/*

Encoding:
  Enabled: false

Rails:
  Enabled: true

Rails/HttpPositionalArguments:
  Enabled: false

Rails/DynamicFindBy:
  Whitelist:
    - find_by_tag
    - find_by_name
    - find_by_tags_from

Metrics/LineLength:
  Max: 120
