require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
   - db/schema.rb
   - vendor/**/*
   - db/**/*

Encoding:
  Enabled: false

Rails:
  Enabled: true

Rails/HttpPositionalArguments:
  Enabled: true
  Exclude:
   - spec/api/**/*

Rails/DynamicFindBy:
  Whitelist:
    - find_by_tag
    - find_by_name
    - find_by_tags_from

Metrics/LineLength:
  Max: 140

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Style/Documentation:
  Description: Document classes and non-namespace modules.
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: "double_quotes"

Metrics/BlockLength:
  Enabled: false
